global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  

  - job_name: "custom-exporter"
    static_configs:
      - targets: ["custom_exporter:8000"]

  - job_name: "windows-exporter"
    static_configs:
      - targets: ["host.docker.internal:9182"]
      
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['host.docker.internal:9187']
